spring:
  h2:
    console:
      enabled: true
  shell:
      interactive:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    generate-dll: false
  datasource:
    initialization-mode: always