DROP TABLE IF EXISTS PUBLISHERS;
CREATE TABLE PUBLISHERS(
PUBLISHER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
PUBLISHER_NAME VARCHAR(255) NOT NULL,
COUNTRY VARCHAR(255)
);

DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(
AUTHOR_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
FIRST_NAME VARCHAR(55) NOT NULL,
LAST_NAME VARCHAR(55)
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  ISBN INT NOT NULL,
  YEAR INT,
  TYPE VARCHAR(255),
  PUBLISHER_ID INT,
  AUTHOR_ID INT,
  FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHERS(PUBLISHER_ID),
  FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
  );

DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  TEXT VARCHAR(255),
  BOOK_ID BIGINT,
  FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID)
);