INSERT INTO PUBLISHERS (`PUBLISHER_NAME`, `COUNTRY`)
VALUES(
	'OREILLY',
	'US'
);
INSERT INTO PUBLISHERS (`PUBLISHER_NAME`, `COUNTRY`)
VALUES(
	'HEAD FIRST',
	'US'
);
INSERT INTO PUBLISHERS (`PUBLISHER_NAME`, `COUNTRY`)
VALUES(
	'PRENTICE HALL',
	'US'
);
INSERT INTO PUBLISHERS (`PUBLISHER_NAME`, `COUNTRY`)
VALUES(
	'MANNING',
	'US'
);







INSERT INTO AUTHORS (`FIRST_NAME`, `LAST_NAME`)
VALUES(
	'JOSHUA',
	'BLOCH'
);
INSERT INTO AUTHORS (`FIRST_NAME`, `LAST_NAME`)
VALUES(
	'BERT',
	'BATES'
);
INSERT INTO AUTHORS (`FIRST_NAME`, `LAST_NAME`)
VALUES(
	'BRUCE',
	'ECKEL'
);
INSERT INTO AUTHORS (`FIRST_NAME`, `LAST_NAME`)
VALUES(
	'KATHY',
	'SIERRA'
);
INSERT INTO AUTHORS (`FIRST_NAME`, `LAST_NAME`)
VALUES(
	'ROBERT',
	'MARTIN'
);
INSERT INTO AUTHORS (`FIRST_NAME`, `LAST_NAME`)
VALUES(
	'MARIO',
	'FUSCO'
);
INSERT INTO AUTHORS (`FIRST_NAME`, `LAST_NAME`)
VALUES(
	'CRAIG',
	'WALLS'
);





INSERT INTO BOOKS (`NAME`, ISBN, YEAR, `TYPE`, PUBLISHER_ID, AUTHOR_ID)
VALUES(
	'EFFECTIVE JAVA',
	123456,
	2001,
	'Computer Science',
	1,
	1
);
INSERT INTO BOOKS (`NAME`, ISBN, YEAR, `TYPE`, PUBLISHER_ID, AUTHOR_ID)
VALUES(
	'JAVA',
	123457,
	2003,
	'Computer Science',
	2,
	2
);
INSERT INTO BOOKS (`NAME`, ISBN, YEAR, `TYPE`, PUBLISHER_ID, AUTHOR_ID)
VALUES(
	'THINKING IN JAVA',
	123458,
	2006,
	'Computer Science',
	3,
	3
);
INSERT INTO BOOKS (`NAME`, ISBN, YEAR, `TYPE`, PUBLISHER_ID, AUTHOR_ID)
VALUES(
	'DESIGN PATTERNS',
	123459,
	2004,
	'Computer Science',
	2,
	4
);
INSERT INTO BOOKS (`NAME`, ISBN, YEAR, `TYPE`, PUBLISHER_ID, AUTHOR_ID)
VALUES(
	'CLEAN CODE',
	123452,
	2008,
	'Computer Science',
	3,
	5
);
INSERT INTO BOOKS (`NAME`, ISBN, YEAR, `TYPE`, PUBLISHER_ID, AUTHOR_ID)
VALUES(
	'JAVA8 IN ACTION',
	123453,
	2014,
	'Computer Science',
	4,
	6
);
INSERT INTO BOOKS (`NAME`, ISBN, YEAR, `TYPE`, PUBLISHER_ID, AUTHOR_ID)
VALUES(
	'SPRING BOOT IN ACTION',
	123455,
	2015,
	'Computer Science',
	4,
	7
);


INSERT INTO COMMENTS (`TEXT`, `BOOK_ID`)
VALUES (
  '1111111111111111111',
	1
);
INSERT INTO COMMENTS (`TEXT`, `BOOK_ID`)
VALUES (
	'22222222222',
	1
);
INSERT INTO COMMENTS (`TEXT`, `BOOK_ID`)
VALUES (
	'44444444444444',
	2
);
INSERT INTO COMMENTS (`TEXT`, `BOOK_ID`)
VALUES (
	'11111111111555555555555511111111',
	3
);
INSERT INTO COMMENTS (`TEXT`, `BOOK_ID`)
VALUES (
	'777777777777777',
	1
);
INSERT INTO COMMENTS (`TEXT`, `BOOK_ID`)
VALUES (
	'TTTTTTTTTTTTTTT',
	4
);
INSERT INTO COMMENTS (`TEXT`, `BOOK_ID`)
VALUES (
	'55555555555555555',
	1
);
INSERT INTO COMMENTS (`TEXT`, `BOOK_ID`)
VALUES (
	'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF',
	2
);
INSERT INTO COMMENTS (`TEXT`, `BOOK_ID`)
VALUES (
	'66666666666666666666',
	1
);
INSERT INTO COMMENTS (`TEXT`, `BOOK_ID`)
VALUES (
	'BBBBBBBBBBBBBBBBBBBBB',
	3
);
INSERT INTO COMMENTS (`TEXT`, `BOOK_ID`)
VALUES (
	'1111111111111111111',
	2
);
