INSERT INTO PUBLISHERS (`NAME`, `COUNTRY`)
VALUES(
	'OREILLY',
	'US'
);
INSERT INTO PUBLISHERS (`NAME`, `COUNTRY`)
VALUES(
	'HEAD FIRST',
	'US'
);
INSERT INTO PUBLISHERS (`NAME`, `COUNTRY`)
VALUES(
	'PRENTICE HALL',
	'US'
);
INSERT INTO PUBLISHERS (`NAME`, `COUNTRY`)
VALUES(
	'MANNING',
	'US'
);







INSERT INTO AUTHORS (`FIRST_NAME`, `LAST_NAME`)
VALUES(
	'JOSHUA',
	'BLOCH'
);
INSERT INTO AUTHORS (`FIRST_NAME`, `LAST_NAME`)
VALUES(
	'BERT',
	'BATES'
);
INSERT INTO AUTHORS (`FIRST_NAME`, `LAST_NAME`)
VALUES(
	'BRUCE',
	'ECKEL'
);
INSERT INTO AUTHORS (`FIRST_NAME`, `LAST_NAME`)
VALUES(
	'KATHY',
	'SIERRA'
);
INSERT INTO AUTHORS (`FIRST_NAME`, `LAST_NAME`)
VALUES(
	'ROBERT',
	'MARTIN'
);
INSERT INTO AUTHORS (`FIRST_NAME`, `LAST_NAME`)
VALUES(
	'MARIO',
	'FUSCO'
);
INSERT INTO AUTHORS (`FIRST_NAME`, `LAST_NAME`)
VALUES(
	'CRAIG',
	'WALLS'
);





INSERT INTO BOOKS (`NAME`, ISBN, YEAR, `TYPE`, PUBLISHER_ID, AUTHOR_ID)
VALUES(
	'EFFECTIVE JAVA',
	123456,
	2001,
	'COMPUTER SCIENCE',
	1,
	1
);
INSERT INTO BOOKS (`NAME`, ISBN, YEAR, `TYPE`, PUBLISHER_ID, AUTHOR_ID)
VALUES(
	'JAVA',
	123457,
	2003,
	'COMPUTER SCIENCE',
	2,
	2
);
INSERT INTO BOOKS (`NAME`, ISBN, YEAR, `TYPE`, PUBLISHER_ID, AUTHOR_ID)
VALUES(
	'THINKING IN JAVA',
	123458,
	2006,
	'COMPUTER SCIENCE',
	3,
	3
);
INSERT INTO BOOKS (`NAME`, ISBN, YEAR, `TYPE`, PUBLISHER_ID, AUTHOR_ID)
VALUES(
	'DESIGN PATTERNS',
	123459,
	2004,
	'COMPUTER SCIENCE',
	2,
	4
);
INSERT INTO BOOKS (`NAME`, ISBN, YEAR, `TYPE`, PUBLISHER_ID, AUTHOR_ID)
VALUES(
	'CLEAN CODE',
	123452,
	2008,
	'COMPUTER SCIENCE',
	3,
	5
);
INSERT INTO BOOKS (`NAME`, ISBN, YEAR, `TYPE`, PUBLISHER_ID, AUTHOR_ID)
VALUES(
	'JAVA8 IN ACTION',
	123453,
	2014,
	'COMPUTER SCIENCE',
	4,
	6
);
INSERT INTO BOOKS (`NAME`, ISBN, YEAR, `TYPE`, PUBLISHER_ID, AUTHOR_ID)
VALUES(
	'SPRING BOOT IN ACTION',
	123455,
	2015,
	'COMPUTER SCIENCE',
	4,
	7
);